### ISSUE TITLE
STUN servers Google

### ISSUE THREAD

**Issue by Piber0** [nickspaargaren/no-google#119]
Hello, shouldn't Google's STUN servers be blocked? On my side, I found these:
stun.l.google.com
stun1.l.google.com
stun2.l.google.com
stun3.l.google.com
stun4.l.google.com

Thank you for your work.

**Comment by Piber0** [comment]
I also found this domain (clients.l.google.com) that allows to block the download of the disk as well as other domains present in this [list ](https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt) (like googleadapis.l.google.com, redirector.googlevideo.com ...)

**Comment by nickspaargaren** [comment]
Hi @Piber0! Thank you for mentioning these additions! We [recently decided](https://github.com/nickspaargaren/no-google/commit/986b5875475ab663d46842d13175ed86bee73bb9) to remove these from the list because there were too many of them.

We have decided to block these domains via regex, see https://github.com/nickspaargaren/no-google#important-regex-filters-not-included-in-blocklist. My advice is to add the regex to your preferred software.
