### ISSUE TITLE
Cook-book for no-google

### ISSUE THREAD

**Issue by szepeviktor** [nickspaargaren/no-google#53]
Is there a sound theory to create these lists
or is it a bit-by-bit job?

Thank you!

**Comment by PoorPocketsMcNewHold** [comment]
Entirely bit by bit currently. I believe @nickspaargaren first started the list by scrapping google domains, but we currently don't have any "automatic scrapping searches" or searching for new domains for all G products. Same goes for our No-A list (and potentially other ones in the future).
I do believe an "automatic recipe" could be made in order to help maintain the whole list and keep it regularly updated with ease.

**Comment by szepeviktor** [comment]
Thank you for your answer.

**Comment by Macqael** [comment]
i also think the list who don't use wildcard must be used in last step too (because for instance metrics) it's easy to google to auto generate news subdomain for metrics, and it take some time to update the list.
So mark the wildcard who block "metrics.google.com" and all it's subdomain instead of the list who list all "xxxxx.metrics.google.com" as recommended list can be a solution.
What it can be useful to is to use a crawler who follow all link on google domain to generate a list of domain come from google website, and after check it's list to see if it's a google domain or not.

**Comment by Jecaperexaa** [comment]
https://github.com/nickspaargaren/no-google/issues/53#issue-806522039

**Comment by Jecaperexaa** [comment]
https://github.com/nickspaargaren/no-google/issues/53#issue-806522039

**Comment by Jecaperexaa** [comment]
https://github.com/nickspaargaren/no-google/issues/53#issuecomment-1401298464

**Comment by Jecaperexaa** [comment]
https://github.com/nickspaargaren/no-google/issues/53#issue-806522039
