### ISSUE TITLE
More domains logged on Android 10 within about 4 hours

### ISSUE THREAD

**Issue by QuickJack** [nickspaargaren/no-google#57]
It seems that there are still lots of domains missing.

lamssettings-pa.googleapis.com
content-autofill.googleapis.com
stun2.l.google.com
regioninfo-pa.googleapis.com
ulp1p-pa.googleapis.com

**Comment by nickspaargaren** [comment]
Hi @QuickJack , Thank you! We will add them later, otherwise your can help us by adding them via de edit button and create a [pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request). We can check the files and merge them with the master.

<img width="263" alt="Screen Shot 2021-02-18 at 10 54 10" src="https://user-images.githubusercontent.com/20847106/108339675-0246c880-71d8-11eb-9c68-f679934076d1.png">

**Comment by nickspaargaren** [comment]
This is perfect, many thanks!
