### ISSUE TITLE
Possible host failures

### ISSUE THREAD

**Issue by gallegonovato** [nickspaargaren/no-google#59]
Good afternoon:

First of all thank you for your work and your hosts.

I have been using them for some time and I have to give you my sincere thanks for them.

I was looking at one of your hosts. More specifically https://raw.githubusercontent.com/nickspaargaren/no-google/master/google-domains

And I don't know if there is a bug in it, or it is like that.  I mean:

httpswww.googletagmanager.com
htps.googletagmanager.com

I do not know if they are right or are:

https://.

I apologize if I'm wrong and they are well placed. 

An hug

**Comment by nickspaargaren** [comment]
Hi @gallegonovato , thank you for your feedback! Most links in this list are scraped from Google (and other search engine) results and dns queries. These links you mentioned are indeed (still) directing to Google servers. It looks like the smart people at Google have made some mistakes.
In conclusion, i think it's best to keep them in the list because in the future they can decide to redirect them or add some function to it.
