### ISSUE TITLE
Here are some experimental regexes we can use

### ISSUE THREAD

**Issue by ghost** [nickspaargaren/no-google#7]
```
# **Experimental** regexes
^(.+[-_.])??google[-_.]
^(.+[-_.])??gstatic[-_.]
^(.+[-_.])??googleapis[-_.]
^(.+[-_.])??withgoogle[-_.]
^(.+[-_.])??googletagmanager[-_.]
^(.+[-_.])??googletagservices[-_.]
^(.+[-_.])??googleusercontent[-_.]
^(.+[-_.])??googlesyndication[-_.]
^(.+[-_.])??chromeexperiments[-_.]
^(.+[-_.])??google-analytics[-_.]
^(.+[-_.])??youtube[-_.]
^(.+[-_.])??waze[-_.]
^(.+[-_.])??doubleclick[-_.]
^(.+[-_.])??firebaseio[-_.]

These **should** block all domains like this: *.<domain>.*.
They certainly need to be improved, for example idk if they work with domains like this: .*.<domain>.*
However, this might be a start.
Sorry if they don't work: actually, I can't test is as I had to remove pihole from my rpi. I'll install it on a zero W the next week.
EDIT: the format was wrong, now you should see it correctly :)
```

**Comment by nickspaargaren** [comment]
Oh, that's very interesting! I'll test it as soon as I can too!

**Comment by PoorPocketsMcNewHold** [comment]
These seems to be working pretty well ! I´ll add them to the readme.

**Comment by scoobydom0** [comment]
Ye but they block more than necessary. For example, a site like f*ck-google.com would be blocked :)

**Comment by nickspaargaren** [comment]
> Ye but they block more than necessary. For example, a site like f*ck-google.com would get blocked :)

Very true, but 'google' is specific enough imo, don't you think?

**Comment by scoobydom0** [comment]
I think we should just block google domains. A domain like : something-google.com is not a google domain for example and we shouldn't include it as it doesn't track the users (as far as we know).
However, if you'd like to block all the sites (including suspicious ones), this is the regex: [-_.]?google[-_.] (i have no idea how these regex were working ahah).
I think that at this point we should only use regex filters and, eventually, make a separate blocklist called something like "others.txt" where we put in all the sites linked to google, but with a different name. We could also convert pihole-google.txt into pihole-google.sh to achieve something like this: https://github.com/mmotti/pihole-regex.
What are your thoughts? (sorry for my english)

**Comment by PoorPocketsMcNewHold** [comment]
This would be a pretty good idea indeed, that way. We could mainly organise the list, between each needs.
I´m mostly someone who still use youtube, so that´s way, someone like me would be able to block everything, except the list with Youtube domains.
Someone else who would like to unblock the Google office suite would be still able without whitelisting every link until Pi-hole unblock it.
I´ll take an extra care of trying to organise that a bit beginning by tomorrow.
Also, despite the ReadMe still encouraging to propose better regex filters, I will decide to reopen this issue too, to be able to have regex suggestions directly there.

**Comment by scoobydom0** [comment]
Ok so, I tried domains these domains (which of course doesn't exist)
- "pihole-scoobydoo.dofcourse.ciao_domaindomain.google.it.com"
-  "pihole-scoobydoo.domain.domaindomain.google.it.com.uk"
and they both get blocked with both the regex filters I wrote, so I really have no idea which is better. The two versions are:
- ^(.+[-_.])??google[-_.]
-  [-.]?google[-.]
- and maybe a third .?google. (which blocks only sites containing .?google., where the ? means that everything behind the word "google" is optional. I still think the third one is the most appropriate one because it blocks only domains of google. A domain containing the work google, followed by '-' or '_' isn't necessarily a google domain as I said. (sorry for the repetitions).
Which type should we use?
However, If you want youtube to continue to go, you should just remove the regex for youtube, and the one for googlevideo as well.

**Comment by scoobydom0** [comment]
Well, I think we can close this.
