### ISSUE TITLE
NOt blocking    well

### ISSUE THREAD

**Issue by hujhujhuj888** [nickspaargaren/no-google#79]
trying   this filter on _firefox91esr   ublock1.39.2_    on DW.COM  website  and ublock showing google.com on green  WTF?!

olso  not blocking ajax.googleapis.com

I thought this filter would be trustworthy  but **NOT**!

**Comment by nickspaargaren** [comment]
Hi @hujhujhuj888, thanks for your comment. If the domain is included in the list it should be blocked. If this is not the case it's a problem on your end.

So my solution is: Check if the domain that isn't blocked is present in the no-google list your using. If it is present, contact the tool you're using, in this case Ublock. Otherwise, if it is not present, we would appreciate a pull request to the list.

I'm closing this now, if you have further questions, feel free to reopen this issue.
